version: '3'

services: 
  api:
    build:
      context: ./api
    environment:
      - ENV=${ENV}
      - HTTP_PORT="${HTTP_PORT}"
      - PROJECT_NAME="${PROJECT_NAME}"
    ports:
      - "${HTTP_PORT}:8080"
    restart: always
    container_name: "${PROJECT_NAME}-api"
    networks:
      - "api_main_net"

networks:
  api_main_net:
    driver: bridge

